### PR TITLE
Miniforge Docker images

### PR DESCRIPTION
**Pull request by xhochy**
This moves the `condaforge/miniforge3` and `condaforge/mambaforge` image over from https://github.com/conda-forge/docker-images and introduces image versioning.

### CODE REVIEW

**Comment by xhochy** [comment]
@conda-forge/core This is ready for review. Secrets are yet missing from this repository but otherwise this works. Multi-platform builds with docker seems like fun.

**Comment by jakirkham** [comment]
Thanks Uwe! 😀

Does this squash images? Less familiar with the `buildx` subcommand

**Comment by xhochy** [comment]
> Thanks Uwe! 😀
> 
> Does this squash images? Less familiar with the `buildx` subcommand

No, you cannot `squash` with `buildx`, you cannot build multiplatform images with `docker build`, and so on. I had quite a rage at the fragmentation of the docker/moby build infrastructure while doing this PR. This PR is the compromise of what I could get out of that fragmentation ecosystem. 

(I put `buildah` on my list of things to learn but didn't get to it)

**Comment by jakirkham** [comment]
Gotcha. Did you want to handle secrets here or in another PR?

**Comment by xhochy** [comment]
> Gotcha. Did you want to handle secrets here or in another PR?

No, added them all now.

**Comment by beckermr** [comment]
Have we considered moving this to azure?

**Comment by xhochy** [comment]
> Have we considered moving this to azure?

No, I kept this on Github Actions as it was before. Happy to do that in a follow-up PR once this one is working.

**Comment by jakirkham** [comment]
Just curious, is there a reason we want to move to Azure? Have no preference personally

**Comment by beckermr** [comment]
We have more workers there and these jobs are long.

**Review by jakirkham — APPROVED** [review]

**Comment by xhochy** [comment]
@beckermr In preparation for the follow-up PR: Can you setup the credentials in Azure? I have no access there.

**Comment by beckermr** [comment]
Yes!

**Comment by xhochy** [comment]
Pushed this branch with changed accounts to master on my fork: https://github.com/xhochy/miniforge-images/runs/1857817921, you can see the final images at https://hub.docker.com/repository/docker/xhochy/mambaforge

**Comment by jakirkham** [comment]
Thanks Uwe! 😄 Went ahead and merged. Let's handle the Azure bits in a new PR 👍

**Pull request merged**
