### PR TITLE
Switch to Azure pipelines

### PR DESCRIPTION
**Pull request by xhochy**
To save resources on Github Actions

### CODE REVIEW

**Comment by xhochy** [comment]
@beckermr Can you activate Azure Pipelines here manually?

**Comment by beckermr** [comment]
Yes sorry. I forgot to do this. I will do it when the kiddos are napping.

**Comment by beckermr** [comment]
OK. This is done but you will need to push to master to get it going. If you send me your azure username, I can add you to the project.

**Comment by xhochy** [comment]
I completely fail to authenticate with Docker Hub in Azure Pipelines: https://dev.azure.com/conda-forge/docker-builds/_build/results?buildId=277595&view=logs&j=ee0d501d-3004-5512-5b07-df873398b1b1&t=0404f5b0-fddd-5a5c-8b0d-7f63cdac6fc6 (this is a build from the main repo, not from the fork). I have used the password and an access token. In both cases that login failed. Logging in to `quay.io` works.

**Comment by beckermr** [comment]
I fixed what appears to be a syntax error in the CI script (`secrets.DH_PASSWORD` vs `DH_PASSWORD`).

**Comment by beckermr** [comment]
I also pushed the same fix to the branch on the main repo.

**Comment by beckermr** [comment]
This one is ready to merge @xhochy!

**Comment by xhochy** [comment]
Thanks @beckermr !

**Pull request merged**
