### PR TITLE
Update image of Ubuntu focal to newer one

### PR DESCRIPTION
**Pull request by hmaarrfk**
Checklist
* [ ] Used a [personal fork of the feedstock to propose changes](https://conda-forge.org/docs/maintainer/updating_pkgs.html#forking-and-pull-requests)
* [ ] Bumped the build number (if the version is unchanged)
* [ ] Reset the build number to `0` (if the version changed)
* [ ] [Re-rendered]( https://conda-forge.org/docs/maintainer/updating_pkgs.html#rerendering-feedstocks ) with the latest `conda-smithy` (Use the phrase <code>@<space/>conda-forge-admin, please rerender</code> in a comment in this PR for automated rerendering)
* [ ] Ensured the license file is being packaged.

### CODE REVIEW

**Comment by hmaarrfk** [comment]
xref: https://github.com/conda-forge/miniforge-images/issues/17

**Review by xhochy — APPROVED** [review]

**Comment by hmaarrfk** [comment]
Hmmm. failures seem strange to me.... maybe i guess try to run locally.

**Comment by hmaarrfk** [comment]
@xhochy did you restart a build? I can never find out how to restart things on Azure.

**Comment by xhochy** [comment]
> @xhochy did you restart a build? I can never find out how to restart things on Azure.

Once all builds have passed, you click on [Details] and then `re-run`, e.g. for the current run you would go to https://github.com/conda-forge/miniforge-images/pull/18/checks?check_run_id=2991323646 The re-run button is already there but in my personal experience, it only actually works once all builds have passed.

**Comment by xhochy** [comment]
The old build logs aren't visible anymore thus I cannot investigate. I sadly see these issues quite often in building the images here. Seems to mostly come down to network connection issues.

**Pull request closed without merging**
